#pragma once

#define SATURATION_MIN_VALUE 0
#define SATURATION_MAX_VALUE 1
#define SATURATION_STEP_VALUE 0.01f
#define SATURATION_DEFAULT_VALUE 0.5f

#define INTENSITY_MIN_VALUE 0
#define INTENSITY_MAX_VALUE 1
#define INTENSITY_STEP_VALUE 0.01f
#define INTENSITY_DEFAULT_VALUE 0.5f

#define CONTRAST_MIN_VALUE 0.5f
#define CONTRAST_MAX_VALUE 1.5f
#define CONTRAST_STEP_VALUE 0.01f
#define CONTRAST_DEFAULT_VALUE 1.0f

#define PARTITIONS_MIN_VALUE 5
#define PARTITIONS_MAX_VALUE 50
#define PARTITIONS_STEP_VALUE 1
#define PARTITIONS_DEFAULT_VALUE 10

#define SUB_DIVISIONS_MIN_VALUE 1
#define SUB_DIVISIONS_MAX_VALUE 10
#define SUB_DIVISIONS_STEP_VALUE 1
#define SUB_DIVISIONS_DEFAULT_VALUE 2